### ISSUE TITLE
E2E Crashes

### ISSUE THREAD

**Issue by kythorn** [whizzball1/ApatheticMobs#4]
I'm trying to install this on an SSP instance of Enigmatica 2 Expert  1.62.

The pack loads, but upon trying to load my save, I get the following exception:

Class 'whizzball1.apatheticmobs.handlers.ApatheticHandler' no access to: class 'net.minecraft.entity.ai.EntityAITasks$EntityAITaskEntry'

I saw there were some recent updates that clarified they weren't fully tested, so I rolled back several versions, but they all had the same error.

Versions attempted:

1.4.1
1.4
1.3
1.2

Please  let me know how I can help provide more information so you can troubleshoot this if it's not an issue you're already aware of.

[11:07:02] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.EntityJoinWorldEvent@70245303:
java.lang.BootstrapMethodError: java.lang.IllegalAccessError: Class 'whizzball1.apatheticmobs.handlers.ApatheticHandler' no access to: class 'net.minecraft.entity.ai.EntityAITasks$EntityAITaskEntry'
	at whizzball1.apatheticmobs.handlers.ApatheticHandler.checkSpawns(ApatheticHandler.java:83) ~[ApatheticHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2851_ApatheticHandler_checkSpawns_EntityJoinWorldEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraft.world.WorldServer.func_175650_b(WorldServer.java:1065) [oo.class:?]
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:860) [axw.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:109) [ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) [ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135) [on.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:142) [chd.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]
Caused by: java.lang.IllegalAccessError: Class 'whizzball1.apatheticmobs.handlers.ApatheticHandler' no access to: class 'net.minecraft.entity.ai.EntityAITasks$EntityAITaskEntry'
	at java.lang.invoke.MethodHandle.sendResolveMethodHandle(MethodHandle.java:1005) ~[?:1.8.0_212]
	at java.lang.invoke.MethodHandle.getCPMethodHandleAt(Native Method) ~[?:1.8.0_212]
	at java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:838) ~[?:1.8.0_212]
	... 16 more
Caused by: java.lang.IllegalAccessException: Class 'whizzball1.apatheticmobs.handlers.ApatheticHandler' no access to: class 'net.minecraft.entity.ai.EntityAITasks$EntityAITaskEntry'
	at java.lang.invoke.MethodHandles$Lookup.checkClassAccess(MethodHandles.java:436) ~[?:1.8.0_212]
	at java.lang.invoke.MethodHandles$Lookup.accessCheckArgRetTypes(MethodHandles.java:665) ~[?:1.8.0_212]
	at java.lang.invoke.MethodHandle.sendResolveMethodHandle(MethodHandle.java:979) ~[?:1.8.0_212]
	at java.lang.invoke.MethodHandle.getCPMethodHandleAt(Native Method) ~[?:1.8.0_212]
	at java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:838) ~[?:1.8.0_212]
	... 16 more

**Comment by whizzball1** [comment]
Looks like my access transformer stopped working. I know how to fix it; for now, give me a bit to tell you what config to change to deal with this.

**Comment by whizzball1** [comment]
Can you please tell me your Forge version?

**Comment by kythorn** [comment]
This pack ships with 14.23.5.2781.

**Comment by whizzball1** [comment]
Can you try updating to at least 14.23.5.2824? I have access to the class in that version.

**Comment by kythorn** [comment]
Sure, no problem, I'll give that a whirl and let you know how it goes.

**Comment by whizzball1** [comment]
Thanks! If that works, then I'll set this version of Forge as a required dependency.

**Comment by kythorn** [comment]
No crashing, thanks!

**Comment by whizzball1** [comment]
Awesome! Changing dependencies for the next version.
