### ISSUE TITLE
Exception on startup with OpenBlcoks

### ISSUE THREAD

**Issue by MatthiasMann** [whizzball1/ApatheticMobs#7]
I have apatheticmobs-1.4.1 and OpenBlocks-1.12.2-1.8.1 installed and see the following messages at startup:

[09:24:44] [Client thread/ERROR] [FML]: Encountered an exception while constructing entity 'minecraft:zombie_pigman'
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_222]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_222]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_222]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_222]
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.apply(EntityEntryBuilder.java:305) [EntityEntryBuilder$ConstructorFactory.class:?]
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.apply(EntityEntryBuilder.java:291) [EntityEntryBuilder$ConstructorFactory.class:?]
	at net.minecraftforge.fml.common.registry.EntityEntry.newInstance(EntityEntry.java:68) [EntityEntry.class:?]
	at net.minecraft.entity.EntityList.func_188429_b(EntityList.java:204) [vi.class:?]
	at openblocks.common.TrophyHandler$Trophy.createEntity(TrophyHandler.java:287) [TrophyHandler$Trophy.class:?]
	at openblocks.common.TrophyHandler.getEntityFromCache(TrophyHandler.java:78) [TrophyHandler.class:?]
	at openblocks.common.TrophyHandler$Trophy.getEntity(TrophyHandler.java:244) [TrophyHandler$Trophy.class:?]
	at openblocks.client.renderer.tileentity.TileEntityTrophyRenderer.renderTrophy(TileEntityTrophyRenderer.java:84) [TileEntityTrophyRenderer.class:?]
	at openblocks.client.renderer.tileentity.TileEntityTrophyRenderer.render(TileEntityTrophyRenderer.java:50) [TileEntityTrophyRenderer.class:?]
	at openblocks.client.renderer.tileentity.TileEntityTrophyRenderer.func_192841_a(TileEntityTrophyRenderer.java:31) [TileEntityTrophyRenderer.class:?]
	at net.minecraftforge.client.ForgeHooksClient.renderTileItem(ForgeHooksClient.java:586) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.tileentity.TileEntityItemStackRenderer.func_192838_a(TileEntityItemStackRenderer.java:121) [buo.class:?]
	at vazkii.botania.client.render.tile.RenderTilePylon$ForwardingTEISR.func_192838_a(RenderTilePylon.java:157) [RenderTilePylon$ForwardingTEISR.class:?]
	at net.minecraft.client.renderer.tileentity.TileEntityItemStackRenderer.func_179022_a(TileEntityItemStackRenderer.java:45) [buo.class:?]
	at reborncore.shields.client.RebornItemStackRenderer.func_179022_a(RebornItemStackRenderer.java:116) [RebornItemStackRenderer.class:?]
	at vswe.stevescarts.renders.ItemStackRenderer.func_179022_a(ItemStackRenderer.java:25) [ItemStackRenderer.class:?]
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:145) [bzw.class:?]
	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:308) [bzw.class:?]
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:347) [bzw.class:?]
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:356) [CCRenderItem.class:?]
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.render(ItemStackRenderer.java:30) [ItemStackRenderer.class:?]
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.render(ItemStackRenderer.java:23) [ItemStackRenderer.class:?]
	at mezz.jei.render.IngredientRenderer.renderSlow(IngredientRenderer.java:69) [IngredientRenderer.class:?]
	at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:189) [IngredientListBatchRenderer.class:?]
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:99) [IngredientGrid.class:?]
	at mezz.jei.gui.overlay.IngredientGridWithNavigation.draw(IngredientGridWithNavigation.java:97) [IngredientGridWithNavigation.class:?]
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:161) [IngredientListOverlay.class:?]
	at mezz.jei.gui.GuiEventHandler.onDrawScreenEventPost(GuiEventHandler.java:94) [GuiEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1667_GuiEventHandler_onDrawScreenEventPost_Post.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:397) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124) [buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at whizzball1.apatheticmobs.handlers.ApatheticHandler.addCap(ApatheticHandler.java:126) ~[ApatheticHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1390_ApatheticHandler_addCap_AttachCapabilitiesEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:691) ~[ForgeEventFactory.class:?]
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:661) ~[ForgeEventFactory.class:?]
	at net.minecraft.entity.Entity.<init>(Entity.java:219) ~[vg.class:?]
	at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:164) ~[vp.class:?]
	at net.minecraft.entity.EntityLiving.<init>(EntityLiving.java:90) ~[vq.class:?]
	at net.minecraft.entity.EntityCreature.<init>(SourceFile:21) ~[vx.class:?]
	at net.minecraft.entity.monster.EntityMob.<init>(EntityMob.java:26) ~[ade.class:?]
	at net.minecraft.entity.monster.EntityZombie.<init>(EntityZombie.java:70) ~[adt.class:?]
	at net.minecraft.entity.monster.EntityPigZombie.<init>(SourceFile:40) ~[adf.class:?]
	... 46 more
[09:24:44] [Client thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.AttachCapabilitiesEvent@2bd52591:
java.lang.NullPointerException: null
	at whizzball1.apatheticmobs.handlers.ApatheticHandler.addCap(ApatheticHandler.java:126) ~[ApatheticHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1390_ApatheticHandler_addCap_AttachCapabilitiesEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:691) [ForgeEventFactory.class:?]
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:661) [ForgeEventFactory.class:?]
	at net.minecraft.entity.Entity.<init>(Entity.java:219) [vg.class:?]
	at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:164) [vp.class:?]
	at net.minecraft.entity.EntityLiving.<init>(EntityLiving.java:90) [vq.class:?]
	at net.minecraft.entity.EntityCreature.<init>(SourceFile:21) [vx.class:?]
	at net.minecraft.entity.monster.EntityMob.<init>(EntityMob.java:26) [ade.class:?]
	at net.minecraft.entity.monster.EntityZombie.<init>(EntityZombie.java:70) [adt.class:?]
	at sun.reflect.GeneratedConstructorAccessor191.newInstance(Unknown Source) [?:1.8.0_222]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [?:1.8.0_222]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [?:1.8.0_222]
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.apply(EntityEntryBuilder.java:305) [EntityEntryBuilder$ConstructorFactory.class:?]
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.apply(EntityEntryBuilder.java:291) [EntityEntryBuilder$ConstructorFactory.class:?]
	at net.minecraftforge.fml.common.registry.EntityEntry.newInstance(EntityEntry.java:68) [EntityEntry.class:?]
	at net.minecraft.entity.EntityList.func_188429_b(EntityList.java:204) [vi.class:?]
	at openblocks.common.TrophyHandler$Trophy.createEntity(TrophyHandler.java:287) [TrophyHandler$Trophy.class:?]
	at openblocks.common.TrophyHandler.getEntityFromCache(TrophyHandler.java:78) [TrophyHandler.class:?]
	at openblocks.common.TrophyHandler$Trophy.getEntity(TrophyHandler.java:244) [TrophyHandler$Trophy.class:?]
	at openblocks.client.renderer.tileentity.TileEntityTrophyRenderer.renderTrophy(TileEntityTrophyRenderer.java:84) [TileEntityTrophyRenderer.class:?]
	at openblocks.client.renderer.tileentity.TileEntityTrophyRenderer.render(TileEntityTrophyRenderer.java:50) [TileEntityTrophyRenderer.class:?]
	at openblocks.client.renderer.tileentity.TileEntityTrophyRenderer.func_192841_a(TileEntityTrophyRenderer.java:31) [TileEntityTrophyRenderer.class:?]
	at net.minecraftforge.client.ForgeHooksClient.renderTileItem(ForgeHooksClient.java:586) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.tileentity.TileEntityItemStackRenderer.func_192838_a(TileEntityItemStackRenderer.java:121) [buo.class:?]
	at vazkii.botania.client.render.tile.RenderTilePylon$ForwardingTEISR.func_192838_a(RenderTilePylon.java:157) [RenderTilePylon$ForwardingTEISR.class:?]
	at net.minecraft.client.renderer.tileentity.TileEntityItemStackRenderer.func_179022_a(TileEntityItemStackRenderer.java:45) [buo.class:?]
	at reborncore.shields.client.RebornItemStackRenderer.func_179022_a(RebornItemStackRenderer.java:116) [RebornItemStackRenderer.class:?]
	at vswe.stevescarts.renders.ItemStackRenderer.func_179022_a(ItemStackRenderer.java:25) [ItemStackRenderer.class:?]
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:145) [bzw.class:?]
	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:308) [bzw.class:?]
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:347) [bzw.class:?]
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:356) [CCRenderItem.class:?]
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.render(ItemStackRenderer.java:30) [ItemStackRenderer.class:?]
	at mezz.jei.plugins.vanilla.ingredients.item.ItemStackRenderer.render(ItemStackRenderer.java:23) [ItemStackRenderer.class:?]
	at mezz.jei.render.IngredientRenderer.renderSlow(IngredientRenderer.java:69) [IngredientRenderer.class:?]
	at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:189) [IngredientListBatchRenderer.class:?]
	at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:99) [IngredientGrid.class:?]
	at mezz.jei.gui.overlay.IngredientGridWithNavigation.draw(IngredientGridWithNavigation.java:97) [IngredientGridWithNavigation.class:?]
	at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:161) [IngredientListOverlay.class:?]
	at mezz.jei.gui.GuiEventHandler.onDrawScreenEventPost(GuiEventHandler.java:94) [GuiEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1667_GuiEventHandler_onDrawScreenEventPost_Post.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:397) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124) [buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

From looking at the code it seems that OpenBlocks is creating an entity with null world?
https://github.com/OpenMods/OpenBlocks/blob/master/src/main/java/openblocks/common/TrophyHandler.java#L287

So maybe adding a null check here?
https://github.com/whizzball1/ApatheticMobs/blob/master/src/main/java/whizzball1/apatheticmobs/handlers/ApatheticHandler.java#L128

**Comment by whizzball1** [comment]
Please test this release! It should hopefully fix it. https://github.com/whizzball1/ApatheticMobs/releases/tag/1.4.1-hotfix

**Comment by MatthiasMann** [comment]
Yes, that worked - thanks
